"""
Main FastAPI application for Sovereign Assistant API.

Entry point for the OpenAI-compatible REST API that Aurora TA will consume.
"""

import logging
import os
from datetime import datetime
from typing import Dict, Any

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

# Load environment variables from .env file BEFORE importing routes
# Routes import auth.py which reads API_KEY at module load time
load_dotenv()

from api.routes import assistants, threads, runs

# Configure logging
logging.basicConfig(
    level=getattr(logging, os.getenv("LOG_LEVEL", "INFO")),
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# Create FastAPI application
app = FastAPI(
    title="Sovereign Assistant API",
    description="OpenAI-compatible REST API for Aurora TA trading operations",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)

# Add CORS middleware for web access
cors_origins = os.getenv("CORS_ORIGINS", "*")
allow_origins = cors_origins.split(",") if cors_origins != "*" else ["*"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================================
# LIFECYCLE EVENTS
# ============================================================================

@app.on_event("startup")
async def startup_event():
    """Initialize system on startup."""
    logger.info("=" * 70)
    logger.info("SOVEREIGN ASSISTANT API STARTUP")
    logger.info("=" * 70)
    logger.info("Initializing database and dependencies...")
    logger.info("System ready for Aurora TA requests")
    logger.info("OpenAPI documentation available at /docs")


@app.on_event("shutdown")
async def shutdown_event():
    """Cleanup on shutdown."""
    logger.info("=" * 70)
    logger.info("SOVEREIGN ASSISTANT API SHUTDOWN")
    logger.info("=" * 70)
    logger.info("Closing database connections...")
    logger.info("System shutdown complete")


# ============================================================================
# HEALTH CHECK ENDPOINT
# ============================================================================

@app.get("/health", summary="Health Check", description="System health status")
async def health_check() -> Dict[str, Any]:
    """
    Health check endpoint.

    Returns:
        Dictionary with status, version, and timestamp
    """
    return {
        "status": "healthy",
        "version": "1.0.0",
        "timestamp": datetime.utcnow().isoformat(),
    }


# ============================================================================
# INCLUDE ROUTERS
# ============================================================================

# Register route modules with proper prefixes
app.include_router(assistants.router, prefix="/v1/assistants")
app.include_router(threads.router, prefix="/v1/threads")
app.include_router(runs.router, prefix="/v1/threads")

logger.info("Routers registered: assistants, threads, runs")


# ============================================================================
# ERROR HANDLING
# ============================================================================

@app.exception_handler(Exception)
async def global_exception_handler(request, exc):
    """
    Global exception handler for unexpected errors.

    Args:
        request: The request that caused the error
        exc: The exception that was raised

    Returns:
        JSON error response
    """
    logger.error(f"Unhandled exception: {str(exc)}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={
            "error": "internal_error",
            "message": "An unexpected error occurred",
            "status_code": 500,
        },
    )


# OpenAPI documentation is automatically generated by FastAPI

# ============================================================================
# APPLICATION INFO
# ============================================================================

if __name__ == "__main__":
    import uvicorn

    logger.info("Starting Sovereign Assistant API...")
    logger.info("Available at: http://localhost:8000")
    logger.info("API documentation at: http://localhost:8000/docs")

    uvicorn.run(
        "api.main:app",
        host=os.getenv("API_HOST", "0.0.0.0"),
        port=int(os.getenv("API_PORT", "8000")),
        reload=True,
    )